### ISSUE TITLE
Running VERY slow

### ISSUE THREAD

**Issue by steinmeierl** [sans-dfir/sift#12]
Sift is running VERY slow in virtual box.  Before running any applications, just closing the terminal window takes 3 seconds (for the fade-out).  My config is as follows:

---Virtual Box Config---

```
   -System
```

Base Memory:   15220 MB
Processors:   4
Boot Order:   Floppy, CD/DVD, Hard Disk
Acceleration:   VT-x/AMD-V, Nested Paging, PAE/NX

```
   -Display
```

Video Memory:   128 MB
Screens:   2
Acceleration:   3D
Remote Desktop Server:   Disabled
Video Capture:   Disabled

```
   -Storage
```

Controller:   IDE
   IDE Primary Master:   SIFT Workstation 3.0 Core Drive.vmdk (Normal, 500.00 GB)
   IDE Primary Slave:     SIFT Workstation 3.0 Cases.vmdk (Normal, 500.00 GB)
   IDE Secondary Master:   [CD/DVD] VBoxGuestAdditions.iso (61.65 MB)

```
   -Audio
```

Host Driver:    Windows DirectSound
Controller:   ICH AC97

```
   -Network
```

Adapter 1:   Intel PRO/1000 MT Desktop (NAT)

```
   -USB
```

Device Filters: 0 (0 active)

```
   -Shared folders
```

Shared Folders: 1

```
   -Description
```

None

---System Specs---

Dell Precision T7500
Processor: Intel(R) Xeon(R) CPU E5606 @ 2.13GHz (4 Cores)
RAM: 20.0 GB
64 Bit Windows 7 Professional

**Comment by morallo** [comment]
It seems to be a [problem of Virtualbox+Ubuntu+Unity3D] (https://www.google.fr/search?q=virtualbox+ubuntu+14.04+slow).
There are many suggested solutions:
- Enable 3D acceleration. I couldn't make 3D acceleration work when converting the existing SIFT VMWare appliance to VirtualBox.
- Enable "Use Host I/O cache" for the SCSI controler (Settings->Storage)
- Disable Unity3D and use Unity2D --> I think this is not possible any more in 14.04.
- Try to create a VBox SIFT workstation from scratch (installing Ubuntu and using sift-bootstrap). This way you may be able to enable 3D acceleration.

However, if all the problems are graphics related, my suggestion would be to switch to a different and lighter desktop environment, for example LXDE.

> $apt-get install -y lxde-icon-theme lxde-core

Then, log-out and in the login prompt click on the white Ubuntu icon close to the username (sansforensics), and choose LXDE.
Note that you won't have the same apps in the menus, you will need to add them manually. For example, the default terminal is not the familiar "gnome-terminal".

Finally, you can try to implement other general tweaks for Linux guests.
- If you have the disk space, try using fully pre-allocated disks instead of "thin-provisioned"
- https://blogs.oracle.com/fatbloke/entry/speeding_up_your_linux_guests
- http://blog.jdpfu.com/2012/09/14/solution-for-slow-ubuntu-in-virtualbox

**Comment by morallo** [comment]
Just FYI, this seems to work much better in VirtualBox 5.0
