### ISSUE TITLE
Installing SIFT on virtual box error

### ISSUE THREAD

**Issue by manoelitonunes** [sans-dfir/sift#207]
Any expert could help me fixing this issue please
I'm trying to install SIFT on a windows 10 virtual box

Result Code: | VBOX_E_FILE_ERROR (0x80BB0004)
-- | --
Digest mismatch (VERR_NOT_EQUAL): 'sift-file1.iso' not found in the 2nd manifest.
Component: | ApplianceWrap
Interface: | IAppliance {8398f026-4add-4474-5bc3-2f9f2140b23e}

Any help will be much appreciated.

**Comment by mwavada** [comment]
Same issue here.  Virtualbox 5.1.30;  SIFT MD5: 8a3159a4f86f552d5695d3b1b9fdbdce. SHA256 is correct in the sift.mf file.  Not sure what the real issue is, but a non-expert workaround can be performed.  I extracted the .ova file using tar -xvf .  I examined the sift.mf, then packed it back up without the manifest using tar -cvf.  Without the sift.mf file, the ova import works.  I'm a hack, so use at your own risk.

**Comment by Manoelitojunior** [comment]
Hi mwavada, thanks for your help, I ditched the virtual box and installed a vVMware and worked fine after that.

**Comment by This-will-be-your-username** [comment]
Another option is to skip import altogether. Change the extension to .tar or just decompress via terminal as @mwavada mentioned. Take the 2 disks (sift-disk1.vmdk, sift-disk2.vmdk) and manually create a new Ubuntu VM using those 2 discs.

**Comment by A9G-Data-Droid** [comment]
I also experienced this problem. Thanks for the pointers on how to resolve. I manually created the VM.
