### ISSUE TITLE
[SALTSTACK][CLI] How to migrate?

### ISSUE THREAD

**Issue by bergernetch** [sans-dfir/sift#209]
Can a Saltstack installation be migrated to CLI?

**Comment by ekristen** [comment]
There shouldn’t be a saltstack install without the cli. 

How did you initially install or get your VM? 

Either way, you can just download the cli and run install and it’ll make sure everything is up to date.

**Comment by bergernetch** [comment]
The Laptop is running Ubuntu and the the saltstack install. This was done about a year ago, now I wanted to upgrade to the current cli setup. As it did not really work, I reinstalled the laptop with a fresh ubuntu and then installed sift-cli, this resulted in a new problem for which I created a new ticket: https://github.com/sans-dfir/sift/issues/225

**Comment by ekristen** [comment]
@bergernetch I responded to your newer issue, the long and the short of it is that you've found a bug we also do not roll back in the face of errors, so all the successes are still successes. So essentially SIFT is 98% installed and since you chose packages-only, its just the underlying software, no config, no GUI alterations, etc.
