### ISSUE TITLE
Latest SIFT doesn't require auth for SMB

### ISSUE THREAD

**Issue by kkttc** [sans-dfir/sift#234]
When connecting to my SIFT SMB session, I noticed it doesn't require authentication.  Is that expected behavior?

**Comment by ekristen** [comment]
Correct. Since this is primarily used for the 508 class room there are certain things assumed like allowing SMB to work without authentication. We are working on potentially separating out some class room specific things from the community edition, but that hasn't happened yet, until that time the VM is built to service 508 primarily.
