### ISSUE TITLE
[CLI] update of packages-only will make full install 

### ISSUE THREAD

**Issue by bergernetch** [sans-dfir/sift#239]
I installed with --mode=packages-only, but a call to sift update will make a full installation out of it. The option --mode=packages-only is not accepted for sift update, just the help screen will be shown.

How can a packages-only installation be updated?

```
dfir@dfir:~$ sudo sift debug
> sift-cli@1.5.1-beta.0-master.154cb2f

Version: 1.5.1-beta.0
Build: master-154cb2f
User: dfir

Config:
version: v2018.08.0
mode: packages-only
user: dfir
```

**Comment by ekristen** [comment]
Looks like you found a bug @bergernetch. I'll fix this as soon as possible.

**Comment by nksCH** [comment]
A colleague had the same problem with a more recent installation of SIFT. I forward his internal report here:
Update with sift-cli is not possible for packages-only installations.   
The update function does not respect the "--mode" option.   
Configurations from the config file are not taken into account as well. 
Therefore packages-only installations will be transformed to vm installations.

```
$ sudo sift debug
[sudo] password for dfir: 
> sift-cli@1.7.1-master.f1177e4

Version: 1.7.1
Build: master-f1177e4
User: dfir

Config:
version: v2018.28.0
mode: packages-only
user: dfir
```

despite the config file states we are on a packages-only installation sift upgrade will use the   
vm.sls salt.state for the upgrade. 

One can see this in the saltstack.log(I removed some lines for better visibillity):   

```
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ubuntu
# [DEBUG   ] Configuration file path: /etc/salt/minion

[CUT-HERE]

# [DEBUG   ] In saltenv 'base', looking at rel_path 'sift/vm.sls' to resolve 'salt://sift/vm.sls'
# [DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/sift/vm.sls' to resolve 'salt://sift/vm.sls'
# [DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://sift/vm.sls'
# [DEBUG   ] No dest file found
# [INFO    ] Fetching file from saltenv 'base', ** done ** 'sift/vm.sls'
# [DEBUG   ] compile template: /var/cache/salt/minion/files/base/sift/vm.sls

[CUT-HERE]

# [PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/sift/vm.sls' using 'jinja' renderer: 0.011430978775
# [DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/sift/vm.sls:
include:
  - sift.repos
  - sift.packages
  - sift.python-packages
  - sift.tools
  - sift.scripts
  - sift.config
```
    
The problem seems to be in the updateArgs:   
     
```
      const updateArgs = [    
      '-l', 'debug', '--local',    
      '--file-root', filepath,    
      '--state-output=terse',    
      '--out=yaml',     
      'state.apply', stateApplyMap[cli['--mode']],     
      `pillar={sift_user: "${siftConfiguration['user']}"}`     
    ] 
```   
    
It is not possible to specify `stateApplyMap[cli['--mode']]` with an update in the cli.   

Proposed fix:    
The mode is already configured in the config file /etc/sift-config    
```  
$ cat /etc/sift-config 
version: v2018.28.0
mode: packages-only
user: dfir
```  

Therefore the state.apply parameter should be derived from the configuration:   
`'state.apply', "${siftConfiguration['mode']}",`
   
So it would look like this:   
```
      const updateArgs = [    
      '-l', 'debug', '--local',    
      '--file-root', filepath,    
      '--state-output=terse',    
      '--out=yaml',     
      `state.apply "${siftConfiguration['mode']}"`,    
      `pillar={sift_user: "${siftConfiguration['user']}"}`     
    ] 
```

**Comment by ekristen** [comment]
That is definitely a bug. Thanks for the report. I’ll take a look.

I’m working on updating the cli tool to have server and desktop modes as that’s more of the standard term and I’ll fix this while I’m in there.
