### ISSUE TITLE
Upgrade from 1.6.1 (v2018.22.0) to v2018.26.1 failed with errors

### ISSUE THREAD

**Issue by sansstudent** [sans-dfir/sift#285]
Hello,
i have some difficulties updating from to version 

when using sift update:

$ sudo sift update
[sudo] password for administrator: 
> sift-cli@1.6.1-master.bde3e23
> sift-version: v2018.22.0
NOTICE: Fixing incorrect Saltstack configuration.
Installing and configuring Saltstack properly ...
> downloading v2018.22.0

....
>> Completed with Failures -- Success: 536, Failure: 3

when using sift upgrade:
$ sudo sift upgrade
> sift-cli@1.6.1-master.bde3e23
> sift-version: v2018.22.0

> downloading v2018.26.1
>> downloading sift-saltstack-v2018.26.1.tar.gz.asc
>> downloading sift-saltstack-v2018.26.1.tar.gz.sha256
>> downloading sift-saltstack-v2018.26.1.tar.gz.sha256.asc
>> downloading sift-saltstack-v2018.26.1.tar.gz

>> Completed with Failures -- Success: 536, Failure: 3

[saltstack.log](https://github.com/sans-dfir/sift/files/2140863/saltstack.log)

**Comment by ekristen** [comment]
Looks like machinae failed to install for some reason. You can try to install it manually. It's a python module.

**Comment by krisgelijkaan** [comment]
maybe because of this ?

p with sudo, you may want sudo's -H flag.
Collecting machinae
  Downloading https://files.pythonhosted.org/packages/e1/32/fcf173886cb51cbba843a9eb4e6550d71c8f5f9aefec08dc08359232e022/machinae-1.4.0.tar.gz
Collecting dnspython3 (from machinae)
  Downloading https://files.pythonhosted.org/packages/f0/bb/f41cbc8eaa807afb9d44418f092aa3e4acf0e4f42b439c49824348f1f45c/dnspython3-1.15.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-t5hD70/dnspython3/setup.py", line 25
        """+"="*78, file=sys.stdout)
                        ^
    SyntaxError: invalid syntax

**Comment by ekristen** [comment]
Closing in favor of one issue https://github.com/sans-dfir/sift/issues/287 for tracking.
