### ISSUE TITLE
The .OVA build caused chaos on the LAN

### ISSUE THREAD

**Issue by MrGentry** [sans-dfir/sift#345]
As soon as I booted up the VM's, it killed the network(host operating system lost WAN routing) and crashed the domain controller and probably the DHCP server running on it.

**Comment by ekristen** [comment]
* When did you download the OVA.
* What OS?
* What virtualization software?
* Where is the domain controller located?

The definition of a VM makes is isolated from the host, by itself the guest os, in this case ubuntu with a bunch of preinstalled packages should not be able to have any affect on it, unless you gave it elevated privileges to the host.

To my knowledge SIFT requires no elevated privileges on the host. There was a package called nfdump, ~3 years ago that attemped to monitor all network traffic the moment the OVA booted up but has since been disabled/removed (I don't recall which).

**Comment by MrGentry** [comment]
DC is Windows Server 2012 running on vmware esxi, workstations are Win10 using vmware workstation 14 for the clients. The domain controller is located on our blade server, though it's only operating network services and not serving the VM's (resources insufficient, so we run client VM's on their windows 10 workstations).

I understand the isolation of the VM, which is why this was so absurd. Funny, it seemed to me like something very similar to the nfdump you're referring to. 

Yeah, I haven't gotten around to doing a packet capture, yet.
