### ISSUE TITLE
Error Code: 100 on package installation when installing on Ubuntu 12 and 14

### ISSUE THREAD

**Issue by ize1** [sans-dfir/sift#36]
I have installed a 64 bit Ubuntu VM (tried both 12 and 14) and am trying to install SIFT via the bootstrap.sh script. Most of the packages (sift-base, sift-scripts, afterglow and almost all others) return the error 'ERROR: Install Failure: [package name] (Error Code: 100)'.

**Comment by echosix** [comment]
Also make sure you have add-apt-repository installed, if it isn't the following will install it.
sudo apt-get install software-properties-common

**Comment by ekristen** [comment]
If you are using the bootstrap script you just need to run it. 

Most likely why you are seeing 100 errors is because another package manager had apt locked.

There are two packages that will error at the moment, dff, guymager

Erik

**Comment by echosix** [comment]
Hi Erik,

I saw the same errors and worked out that add-apt-repository was not installed, Ubuntu amd64 server 14.04.  It foxed me for a while because I didn't see this on other installs I had done to other machines using the same iso.

The script needs to check to see if add-apt-repository is available otherwise the repositories are not added and the script fails to fetch the packages and reports the 100 errors.

Regards,
Jon.

**Comment by ekristen** [comment]
I did confirm a bug. The package that provides that command changed between the two. I'll get the script fixed today. 

Thanks

**Comment by ekristen** [comment]
This has been fixed. Please try the script again.
