### ISSUE TITLE
Issues updating SIFT via SALT

### ISSUE THREAD

**Issue by zaqes** [sans-dfir/sift#623]
I got 32 failed, seems to be mostly around volatility

[saltstack.log](https://github.com/teamdfir/sift/files/14309366/saltstack.log)

**Comment by ekristen** [comment]
Yup looks like some python install errors. We are not seeing any such build failures currently in any test environments. 

- What OS version are you on?
- What architecture are you on?
- What commands did you use to install?
-

**Comment by zaqes** [comment]
Ubuntu 20.04.6 LTS
x64
cast install teamdfir/sift-saltstack

**Comment by digitalsleuth** [comment]
Hi @zaqes , it looks like this issue is focused around m2crypto, which recently (3 days ago) removed all support for python2. m2crypto is required for dpapick, which is a requirement for a feature in volatility. Volatility is a requirement for vshot, which is where all of the errors are coming from.

The latest version of m2crypto which supports python2 is 0.40.1, so I'll do some testing with that and submit a PR with the changes.

**Comment by ekristen** [comment]
v2024.02.24 is out which should resolve the problem.

**Comment by zaqes** [comment]
Thanks, works now!
