### ISSUE TITLE
Disable automount

### ISSUE THREAD

**Issue by DigiAngel** [sans-dfir/sift#65]
Hey all...I know this isn't specifically a SIFT question, but I am unable to stop Ubuntu from automounting, which is bad forensically.  I've tried the dconf-editor route, but no good...I turn on my external drive bay and /media/usb0 is automatically mounted.  Any help with this?  Thank you.

**Comment by DigiAngel** [comment]
No takers on this eh?

**Comment by JohnEbert** [comment]
Besides setting dconf-editor org.gnome.desktop.media handling Automount off, which will still permit r/w mount if you click the device icon, enforce read-only control to that by adding some lines like these examples to your /etc/fstab configuration file. It will permit all users to mount and umount but it will be read-only for the first USB device with up to 3 partitions protected which is attached after /dev/sdb1 (/cases in SIFT). The next attached /dev/sdd1 device will mount as r/w and can be your evidence collection drive.

# Forensic configuration permit read-only for the first USB device attached (evidence)
# Includes 3 partitions as a precaution in case we forgot to check for more than one with "fdisk -l"
# <file system>	<mount point>	<type>	<options>					<dump>	<pass>
/dev/sdc1			/media/sdc1	auto		ro,users,noauto,noexec		0		0
/dev/sdc2			/media/sdc2	auto		ro,users,noauto,noexec		0		0
/dev/sdc3			/media/sdc3	auto		ro,users,noauto,noexec		0		0

**Comment by DigiAngel** [comment]
Thanks John....I'll give that a go.

**Comment by JohnEbert** [comment]
I added two more entries to the fstab example because I realized linux often places a swap file on partition 5 that may not want to be modified during an investigation.

Take note that the methods of using dconf-editor and fstab to control read-only access does have the possible exceptions of not working if the file system of the device under invetigation i not undertood by the examining SIFT workstation. I have experienced this exception with the Boot-Repair-Disk on a Kingston Datatraveler USB stick (at http://sourceforge.net/p/boot-repair-cd/home/Home/) and it mounted as read-write using the users-name and the device name as the mount point (/media/SANSFORENSICS/KINGSTON) in spite of the controls in place. Use a hardware write blocker as your first choice if available.

**Comment by bergernetch** [comment]
If you boot Kali in Forensics mode, no disk is auto-mounted: http://docs.kali.org/general-use/kali-linux-forensics-mode

Of course, a hardware write blocker is first choice, but it would still be nice to have a default or at least a simple option to disable auto-mounting completely.
