### ISSUE TITLE
SIFT Bootstrap login issue

### ISSUE THREAD

**Issue by delbs** [sans-dfir/sift#92]
Hey guys, I've been using a SIFT workstation VM for a while successfully. I have just rebuilt it on a 14.04 Ubuntu stock image with the SIFT Bootstrap on a physical machine. I had an existing user account on the machine and now that SIFT is installed I attempt to login and it successfully accepts me password but then bounces back to the login prompt straight away. 

I can login via cli but not the Unity login manager gui.  It seems to be a permissions issue with the users home directory but I'm not sure if my user account I created is fine or I have to have sansforensics created? As it doesn't currently exist.

Anyone have this issue before?

**Comment by ekristen** [comment]
It bootstraps using the whatever user you install the script with. You should run the script using sudo from within unity desktop.

**Comment by delbs** [comment]
Heĺlo

Thanks for the response. I have done exactly that. I have installed it
using sudo

Thanks
Nathan

**Comment by spawankumar** [comment]
Hello, 
I did install the script using Sudo in unity desktop. But didnt have enough luck logging in. 
I'm able to login  via CLI but unable to jump on Unity desktop by using startx.
Kindly advice
P

**Comment by delbs** [comment]
Thanks for the reply, i just fixed it by making the permissions on my home
folder 774 octal rights and i can login, perhaps i installed it under the
wrong user. im not sure. All solved though.

Thanks,
Nathan

**Comment by ekristen** [comment]
What base image did you use to start with? Ubuntu? What version? Desktop or server?

**Comment by spawankumar** [comment]
I've ubuntu 14.04 desktop 64 bit. it's installed as a dual boot with Windows 10. 
Thanks a lot

**Comment by ekristen** [comment]
Did you install from a terminal on the unity desktop?

**Comment by spawankumar** [comment]
Yeah. I did install it from terminal of unity desktop. 
I did 
$Sudo -s
// Entered Username & password
then 
$wget --quiet -O - https://raw.github.com/sans-dfir/sift-bootstrap/master/bootstrap.sh | sudo bash -s -- -i -s -y 

I had this issue after I rebooted my system and until then I was able to login usually.
Please advice
P

**Comment by ekristen** [comment]
The `sudo -s` is the problem. 

While from the terminal `echo $SUDO_USER` shows the correct username, it appears the script is getting `root` as the value of $SUDO_USER at https://github.com/sans-dfir/sift-bootstrap/blob/master/bootstrap.sh#L693 and https://github.com/sans-dfir/sift-bootstrap/blob/master/bootstrap.sh#L693

You are unable to login because your $HOME directory is no longer owned by your user.

The script should not be run under these conditions and I'll see what I can do to prevent this in the future.

**Comment by ekristen** [comment]
Actually the problem is the double use of `sudo`, using `sudo -s` isn't big deal until you sudo again in the wget command. This leads  to the $SUDO_USER being set to `root` while leaving the $HOME directory set to your original user home directory path.

This leads to the script changing all the permissions on your home directories to root.

You need to remove one of the sudo and this won't happen anymore.

@delbs while you didn't give me step by step on how you installed, I imagine you did something similar to @spawankumar.

**Comment by spawankumar** [comment]
Thanks a lot @ekristen. You're help is very much appreciated!
Regards
P

**Comment by ekristen** [comment]
Bottom Line: Do not use a double sudo. I'll try and put in some sort of check for this to error out if this is done.

**Comment by Fetchered** [comment]
@ekristen Can we open this up again? I have 3 SIFT kits on 3 different machines (all VM) and all seem to have this same issue. It doesn't appear to be an update issue, but potentially a graphics issue within the SIFT. This seems to have occurred after I installed the bleeding-gums version of john (1.80) but it could be a coincidence. After the install of john I restarted a few times with no issue. Just now I was using the machine, and it locked up. After forcing the machine to shut down and restart the host, I can't get back in. None of the fixes above have resolved the issue, and it doesn't appear to be an ownership problem either.

Any thoughts?

**Comment by ekristen** [comment]
We can, but I don't think this is a SIFT related issue. I think it is a ubuntu and VM hypervisor issue.  Feel free to get your logs up somewhere and I can try and help figure it out. dmesg, messages, etc should all help with troubleshooting login issues.
